function Home() {
  return (
    <div>
      <div id="main" style={{ backgroundColor: 'black', height: '40rem' }}>
        홈입니다.
      </div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
      <div>홈입니다.</div>
    </div>
  );
}

export default Home;
